################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_bqueue.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_camera.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_cpuload.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_lcd.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_postprocess.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/main.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/secure_nsc.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/stm32_lcd_ex.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/stm32n6xx_hal_msp.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/stm32n6xx_hal_timebase_threadx.c \
E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/stm32n6xx_it.c \
../Application/User/Core/syscalls.c \
../Application/User/Core/sysmem.c 

OBJS += \
./Application/User/Core/app.o \
./Application/User/Core/app_bqueue.o \
./Application/User/Core/app_camera.o \
./Application/User/Core/app_cpuload.o \
./Application/User/Core/app_lcd.o \
./Application/User/Core/app_postprocess.o \
./Application/User/Core/main.o \
./Application/User/Core/secure_nsc.o \
./Application/User/Core/stm32_lcd_ex.o \
./Application/User/Core/stm32n6xx_hal_msp.o \
./Application/User/Core/stm32n6xx_hal_timebase_threadx.o \
./Application/User/Core/stm32n6xx_it.o \
./Application/User/Core/syscalls.o \
./Application/User/Core/sysmem.o 

C_DEPS += \
./Application/User/Core/app.d \
./Application/User/Core/app_bqueue.d \
./Application/User/Core/app_camera.d \
./Application/User/Core/app_cpuload.d \
./Application/User/Core/app_lcd.d \
./Application/User/Core/app_postprocess.d \
./Application/User/Core/main.d \
./Application/User/Core/secure_nsc.d \
./Application/User/Core/stm32_lcd_ex.d \
./Application/User/Core/stm32n6xx_hal_msp.d \
./Application/User/Core/stm32n6xx_hal_timebase_threadx.d \
./Application/User/Core/stm32n6xx_it.d \
./Application/User/Core/syscalls.d \
./Application/User/Core/sysmem.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Core/app.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_bqueue.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_bqueue.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_camera.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_camera.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_cpuload.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_cpuload.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_lcd.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_lcd.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/app_postprocess.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/app_postprocess.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/main.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/main.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/secure_nsc.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/secure_nsc.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32_lcd_ex.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/stm32_lcd_ex.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32n6xx_hal_msp.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/stm32n6xx_hal_msp.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32n6xx_hal_timebase_threadx.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/stm32n6xx_hal_timebase_threadx.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32n6xx_it.o: E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/Core/Src/stm32n6xx_it.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/%.o Application/User/Core/%.su Application/User/Core/%.cyclo: ../Application/User/Core/%.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32N647xx -DBSP_UART_RX_DISABLE -DTX_SINGLE_MODE_SECURE -DTX_INCLUDE_USER_DEFINE_FILE -DTX_HAS_PARALLEL_NETWORKS=0 -DTX_EXECUTION_PROFILE_ENABLE -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_THREADX -DLL_ATON_SW_FALLBACK -c -I../../../Appli/Core/Inc -I../../../Secure_nsclib -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/Include -I"E:/Software_Package/Drivers/BSP/NORFlash" -I"E:/Software_Package/Drivers/BSP/HyperRAM" -I"E:/Software_Package/Drivers/BSP/LED" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/LCD" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Drivers/BSP/BUS" -I"E:/Software_Package/Drivers/BSP/UART" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Drivers/CMSIS/DSP/Include" -I"E:/Software_Package/Middlewares/THREADX/ports/cortex_m55/gnu/inc" -I"E:/Software_Package/Middlewares/THREADX/common/inc" -I"E:/Software_Package/Middlewares/THREADX/utility/execution_profile_kit" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/ThreadX/App" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/isp/Inc" -I"E:/Software_Package/Middlewares/STM32_MW_ISP/evision/Inc" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_ISP" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors" -I"E:/Software_Package/Middlewares/STM32_MW_CAMERA/sensors/imx335" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Appli/STM32_MW_CAMERA" -I"E:/Software_Package/Middlewares/AI/Inc" -I"E:/Software_Package/Middlewares/AI/Npu/ll_aton" -I"E:/Software_Package/Middlewares/AI/Npu/Devices/STM32N6XX" -I"E:/Software_Package/Middlewares/STM32_VISION_MODELS_PP/Inc" -I"E:/Software_Package/STM32Cube_FW_N6_V1.0.0/Utilities/lcd" -I"E:/Software_Package/Projects/99_Applications/991_AI_People_Detection/Model" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-Core

clean-Application-2f-User-2f-Core:
	-$(RM) ./Application/User/Core/app.cyclo ./Application/User/Core/app.d ./Application/User/Core/app.o ./Application/User/Core/app.su ./Application/User/Core/app_bqueue.cyclo ./Application/User/Core/app_bqueue.d ./Application/User/Core/app_bqueue.o ./Application/User/Core/app_bqueue.su ./Application/User/Core/app_camera.cyclo ./Application/User/Core/app_camera.d ./Application/User/Core/app_camera.o ./Application/User/Core/app_camera.su ./Application/User/Core/app_cpuload.cyclo ./Application/User/Core/app_cpuload.d ./Application/User/Core/app_cpuload.o ./Application/User/Core/app_cpuload.su ./Application/User/Core/app_lcd.cyclo ./Application/User/Core/app_lcd.d ./Application/User/Core/app_lcd.o ./Application/User/Core/app_lcd.su ./Application/User/Core/app_postprocess.cyclo ./Application/User/Core/app_postprocess.d ./Application/User/Core/app_postprocess.o ./Application/User/Core/app_postprocess.su ./Application/User/Core/main.cyclo ./Application/User/Core/main.d ./Application/User/Core/main.o ./Application/User/Core/main.su ./Application/User/Core/secure_nsc.cyclo ./Application/User/Core/secure_nsc.d ./Application/User/Core/secure_nsc.o ./Application/User/Core/secure_nsc.su ./Application/User/Core/stm32_lcd_ex.cyclo ./Application/User/Core/stm32_lcd_ex.d ./Application/User/Core/stm32_lcd_ex.o ./Application/User/Core/stm32_lcd_ex.su ./Application/User/Core/stm32n6xx_hal_msp.cyclo ./Application/User/Core/stm32n6xx_hal_msp.d ./Application/User/Core/stm32n6xx_hal_msp.o ./Application/User/Core/stm32n6xx_hal_msp.su ./Application/User/Core/stm32n6xx_hal_timebase_threadx.cyclo ./Application/User/Core/stm32n6xx_hal_timebase_threadx.d ./Application/User/Core/stm32n6xx_hal_timebase_threadx.o ./Application/User/Core/stm32n6xx_hal_timebase_threadx.su ./Application/User/Core/stm32n6xx_it.cyclo ./Application/User/Core/stm32n6xx_it.d ./Application/User/Core/stm32n6xx_it.o ./Application/User/Core/stm32n6xx_it.su ./Application/User/Core/syscalls.cyclo ./Application/User/Core/syscalls.d ./Application/User/Core/syscalls.o ./Application/User/Core/syscalls.su ./Application/User/Core/sysmem.cyclo ./Application/User/Core/sysmem.d ./Application/User/Core/sysmem.o ./Application/User/Core/sysmem.su

.PHONY: clean-Application-2f-User-2f-Core

